/**
 * Maintenance orders list (STRUCTURE §4). Filterable by status and type (corrective vs
 * preventive), keyset-paginated (D-014); row click opens the order workbench. "New" creates
 * a CORRECTIVE order only — PREVENTIVE orders are generated by a plan's run.
 */

import { Link, useNavigate } from "@tanstack/react-router";
import { useState } from "react";

import { formatDate } from "@/lib/format";
import { useMe } from "@/lib/session";
import { DataGrid, type DataGridColumn } from "@/components/DataGrid";
import { StatusPill } from "@/components/StatusPill";
import { useEquipmentLookup, useMaintenanceOrders } from "@/modules/maintenance/hooks";
import type {
  MaintenanceOrder,
  MaintenanceOrderStatus,
  MaintenanceOrderType,
} from "@/modules/maintenance/types";

export function MaintenanceOrderListPage() {
  const navigate = useNavigate();
  const me = useMe();
  const canManage = (me.data?.permissions ?? []).includes("maintenance.order.manage");
  const [status, setStatus] = useState<MaintenanceOrderStatus | "">("");
  const [orderType, setOrderType] = useState<MaintenanceOrderType | "">("");

  const orders = useMaintenanceOrders({
    ...(status ? { status } : {}),
    ...(orderType ? { order_type: orderType } : {}),
  });
  const equipment = useEquipmentLookup();
  const rows = orders.data?.pages.flatMap((page) => page.items) ?? [];

  const equipmentLabel = (id: string) => {
    const unit = equipment.data?.items.find((e) => e.id === id);
    return unit ? `${unit.code} — ${unit.name}` : id;
  };

  const columns: DataGridColumn<MaintenanceOrder>[] = [
    { key: "order_number", header: "Order", render: (row) => row.order_number, width: "140px" },
    { key: "equipment", header: "Equipment", render: (row) => equipmentLabel(row.equipment_id) },
    { key: "order_type", header: "Type", render: (row) => row.order_type, width: "110px" },
    { key: "description", header: "Description", render: (row) => row.description },
    {
      key: "scheduled_date",
      header: "Scheduled",
      render: (row) => formatDate(row.scheduled_date),
      width: "120px",
    },
    { key: "status", header: "Status", render: (row) => <StatusPill status={row.status} />, width: "120px" },
  ];

  const filterControl = "rounded-control border border-line bg-surface px-2 py-1.5 text-sm text-ink";

  return (
    <div>
      <div className="flex items-center justify-between">
        <h1 className="text-[22px] font-[650] tracking-[-0.01em] text-ink">Maintenance orders</h1>
        {canManage && (
          <Link
            to="/maintenance/orders/new"
            className="btn-ink"
          >
            New corrective order
          </Link>
        )}
      </div>

      <div className="mt-4 flex gap-2">
        <select
          value={status}
          onChange={(event) => setStatus(event.target.value as MaintenanceOrderStatus | "")}
          className={filterControl}
        >
          <option value="">All statuses</option>
          <option value="DRAFT">Draft</option>
          <option value="SCHEDULED">Scheduled</option>
          <option value="IN_PROGRESS">In progress</option>
          <option value="COMPLETED">Completed</option>
          <option value="CANCELLED">Cancelled</option>
        </select>
        <select
          value={orderType}
          onChange={(event) => setOrderType(event.target.value as MaintenanceOrderType | "")}
          className={filterControl}
        >
          <option value="">All types</option>
          <option value="CORRECTIVE">Corrective</option>
          <option value="PREVENTIVE">Preventive</option>
        </select>
      </div>

      <div className="mt-4">
        <DataGrid
          columns={columns}
          rows={rows}
          rowKey={(row) => row.id}
          onRowClick={(row) => void navigate({ to: "/maintenance/orders/$orderId", params: { orderId: row.id } })}
          loading={orders.isPending}
          emptyMessage="No maintenance orders. Create a corrective order, or run a preventive plan."
          hasMore={orders.hasNextPage}
          onLoadMore={() => void orders.fetchNextPage()}
          loadingMore={orders.isFetchingNextPage}
          label="Maintenance orders"
        />
      </div>
    </div>
  );
}
