/**
 * Mirrors backend `app/modules/maintenance/schemas.py` (STRUCTURE §4). PLAN 15.9: equipment
 * and maintenance-plan masters carry a user-supplied immutable `code`; a maintenance order is
 * a numbered document (MNT-). Orders created via the API are always CORRECTIVE — PREVENTIVE
 * orders only come from a plan's generation run. Money/quantities are decimal strings (D-015).
 */

export type EquipmentStatus = "ACTIVE" | "INACTIVE" | "RETIRED";

export interface EquipmentCreate {
  code: string;
  name: string;
  description?: string | null;
  status?: EquipmentStatus;
  location?: string | null;
  manufacturer?: string | null;
  model?: string | null;
  serial_number?: string | null;
  commissioned_date?: string | null;
  cost_center_id?: string | null;
  notes?: string | null;
}

export type EquipmentUpdate = Partial<Omit<EquipmentCreate, "code">>;

export interface Equipment {
  id: string;
  code: string;
  name: string;
  description: string | null;
  status: EquipmentStatus;
  location: string | null;
  manufacturer: string | null;
  model: string | null;
  serial_number: string | null;
  commissioned_date: string | null;
  cost_center_id: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

// --- Maintenance orders -------------------------------------------------------
//
// CORRECTIVE: created ad-hoc against ACTIVE equipment — born SCHEDULED when a scheduled_date
// is given, else DRAFT. PREVENTIVE: generated by a plan's run, born SCHEDULED. Lifecycle:
// DRAFT -> (schedule) -> SCHEDULED -> (start) -> IN_PROGRESS -> (complete) -> COMPLETED;
// complete is also allowed straight from SCHEDULED; CANCELLED from any non-terminal state.
// Completing records actual_cost on the order only (record-only, no GL posting, D-051).

export type MaintenanceOrderType = "CORRECTIVE" | "PREVENTIVE";

export type MaintenanceOrderStatus =
  | "DRAFT"
  | "SCHEDULED"
  | "IN_PROGRESS"
  | "COMPLETED"
  | "CANCELLED";

export interface MaintenanceOrderCreate {
  equipment_id: string;
  description: string;
  scheduled_date?: string | null;
  estimated_cost?: string | null;
  assigned_to?: string | null;
  notes?: string | null;
}

export interface MaintenanceOrderUpdate {
  description?: string | null;
  estimated_cost?: string | null;
  assigned_to?: string | null;
  notes?: string | null;
}

export interface MaintenanceOrder {
  id: string;
  order_number: string;
  order_type: MaintenanceOrderType;
  status: MaintenanceOrderStatus;
  equipment_id: string;
  maintenance_plan_id: string | null;
  description: string;
  scheduled_date: string;
  completed_date: string | null;
  estimated_cost: string | null;
  actual_cost: string | null;
  assigned_to: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface ScheduleOrderPayload {
  scheduled_date: string;
}

export interface CompleteOrderPayload {
  actual_cost?: string | null;
  completed_date?: string | null;
}

// --- Maintenance plans --------------------------------------------------------
//
// Interval-based preventive plans: ACTIVE plans generate one PREVENTIVE order per due date
// when the run executes; INACTIVE plans are skipped. code/equipment_id are immutable. A
// changed interval applies from the NEXT advance — it never retro-shifts next_due_date.

export type MaintenancePlanStatus = "ACTIVE" | "INACTIVE";

export type IntervalUnit = "DAYS" | "WEEKS" | "MONTHS";

export interface MaintenancePlanCreate {
  code: string;
  name: string;
  equipment_id: string;
  interval_value: number;
  interval_unit: IntervalUnit;
  task_description: string;
  start_date?: string | null;
  estimated_cost?: string | null;
}

export interface MaintenancePlanUpdate {
  name?: string | null;
  interval_value?: number | null;
  interval_unit?: IntervalUnit | null;
  task_description?: string | null;
  estimated_cost?: string | null;
}

export interface MaintenancePlan {
  id: string;
  code: string;
  name: string;
  equipment_id: string;
  status: MaintenancePlanStatus;
  interval_value: number;
  interval_unit: IntervalUnit;
  task_description: string;
  last_generated_date: string | null;
  next_due_date: string;
  estimated_cost: string | null;
  created_at: string;
  updated_at: string;
}

export interface RunPreventiveResult {
  as_of_date: string;
  plans_due: number;
  orders_generated: MaintenanceOrder[];
}
