"""Maintenance constants (STRUCTURE §3): the equipment / order / plan enums + permission keys + the
maintenance-order document type / number sequence / docflow links, registered into the core RBAC
catalog at import (D-009).

A SINGLE file (STRUCTURE §8.4: split into a constants/ package only at the 400-line cap) — PLAN
9.2's small PM core sits well under that.

IDENTITY + NUMBERING (D-051). The two MASTERS carry no gapless document number: ``Equipment`` and
``MaintenancePlan`` use a USER-SUPPLIED ``code`` unique per tenant (the work-centre / item-code
master precedent). A MAINTENANCE ORDER, by contrast, IS a posted document in the D-012 sense: it
registers in core_documents and claims a gapless number at creation.

PREFIX CHOICE (D-051). The order prefix is **"MNT-"** (maintenance), NOT "MO-": "MO-" is already the
manufacturing PRODUCTION-order prefix, and "WO-" (work order) was the alternative but "MNT-" reads
unambiguously as maintenance and never collides with PO-/GR-/SO-/DN-/MO-/MRP-/QL-.

SCOPE (s4hana-parity §QM/PM, D-051). v1 is equipment + corrective/preventive orders + interval
plans.
No functional locations, no notifications, no measurement points/counters, no task lists. A
maintenance order tracks a free-text description + labour/cost as simple amounts; spare-part stock
issue and a PM→FI GL posting are documented laters (the cost is recorded on the order, record-only).
"""

from enum import StrEnum

from app.core.rbac import register_permissions


class EquipmentStatus(StrEnum):
    """Lifecycle of a piece of EQUIPMENT (PLAN 9.2, D-051). A flat equipment register — no
    functional location hierarchy (out of v1 scope).

    - **ACTIVE** — in service; corrective orders may be raised and preventive plans may generate
      orders against it. The default at creation.
    - **INACTIVE** — temporarily out of service (e.g. mothballed). Existing orders stay; a new
      CORRECTIVE order cannot be raised against it (v1 rule: a maintenance order targets ACTIVE
      equipment only).
    - **RETIRED** — permanently decommissioned. Terminal; like INACTIVE it blocks new orders.
    """

    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    RETIRED = "RETIRED"


class MaintenanceOrderType(StrEnum):
    """How a MAINTENANCE ORDER originated (PLAN 9.2, D-051).

    - **CORRECTIVE** — a break-fix order created AD-HOC against a piece of equipment (a breakdown /
      repair). It has no plan link.
    - **PREVENTIVE** — a scheduled order GENERATED by an interval-based maintenance PLAN's run. It
      carries ``maintenance_plan_id`` and a plan→order docflow edge.
    """

    CORRECTIVE = "CORRECTIVE"
    PREVENTIVE = "PREVENTIVE"


class MaintenanceOrderStatus(StrEnum):
    """Lifecycle of a MAINTENANCE ORDER (PLAN 9.2, D-051). The service owns every transition
    (CLAUDE.md rule 7).

    - **DRAFT** — created (a corrective order with no schedule yet). Editable via schedule/cancel.
    - **SCHEDULED** — given a planned ``scheduled_date`` and ready to execute. A PREVENTIVE order is
      born SCHEDULED (the run sets its ``scheduled_date`` = the plan's due date); a CORRECTIVE order
      is created DRAFT or SCHEDULED.
    - **IN_PROGRESS** — work has started.
    - **COMPLETED** — work finished; ``actual_cost`` + ``completed_date`` are recorded. Terminal.
      v1 records the cost ON THE ORDER only (record-only — no GL posting, D-051).
    - **CANCELLED** — abandoned before completion (DRAFT/SCHEDULED/IN_PROGRESS). Terminal.
    """

    DRAFT = "DRAFT"
    SCHEDULED = "SCHEDULED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class MaintenancePlanStatus(StrEnum):
    """Lifecycle of a MAINTENANCE PLAN (PLAN 9.2, D-051). A plan defines a recurring preventive task
    on a piece of equipment; the generation run creates orders from ACTIVE plans.

    - **ACTIVE** — the run considers it: when ``next_due_date <= as_of`` it generates a PREVENTIVE
      order and advances the plan. The default at creation.
    - **INACTIVE** — paused: the run skips it (no orders generated) until reactivated.
    """

    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class IntervalUnit(StrEnum):
    """The UNIT of a maintenance plan's preventive interval (PLAN 9.2, D-051). ``interval_value`` ×
    this unit is the recurrence (e.g. every 3 MONTHS). v1 is purely TIME-based — counter/performance
    intervals need measurement points, which are out of scope.

    - **DAYS** / **WEEKS** / **MONTHS** — the interval is advanced by N calendar days/weeks/months
      from the last generated due date (MONTHS uses calendar-month arithmetic, D-051).
    """

    DAYS = "DAYS"
    WEEKS = "WEEKS"
    MONTHS = "MONTHS"


# --- Permissions (D-009): one key per guarded endpoint action -----------------
# Equipment + plan masters split read/manage; the ORDER splits read/manage/complete because
# COMPLETE records the actual cost (a distinct, value-bearing action — the journal.post / quality
# .decide precedent for separating the cost-recording transition from plain edits). The PLAN gets a
# dedicated ``.run`` key for the generate-due-orders run (segregation of duties: running the
# generator is a maintenance-planner act, distinct from authoring a plan).
MAINTENANCE_EQUIPMENT_READ = "maintenance.equipment.read"
MAINTENANCE_EQUIPMENT_MANAGE = "maintenance.equipment.manage"
MAINTENANCE_ORDER_READ = "maintenance.order.read"
MAINTENANCE_ORDER_MANAGE = "maintenance.order.manage"
MAINTENANCE_ORDER_COMPLETE = "maintenance.order.complete"
MAINTENANCE_PLAN_READ = "maintenance.plan.read"
MAINTENANCE_PLAN_MANAGE = "maintenance.plan.manage"
MAINTENANCE_PLAN_RUN = "maintenance.plan.run"

register_permissions(
    MAINTENANCE_EQUIPMENT_READ,
    MAINTENANCE_EQUIPMENT_MANAGE,
    MAINTENANCE_ORDER_READ,
    MAINTENANCE_ORDER_MANAGE,
    MAINTENANCE_ORDER_COMPLETE,
    MAINTENANCE_PLAN_READ,
    MAINTENANCE_PLAN_MANAGE,
    MAINTENANCE_PLAN_RUN,
    descriptions={
        MAINTENANCE_EQUIPMENT_READ: "Read equipment",
        MAINTENANCE_EQUIPMENT_MANAGE: "Create and edit equipment",
        MAINTENANCE_ORDER_READ: "Read maintenance orders",
        MAINTENANCE_ORDER_MANAGE: "Create, schedule, start and cancel maintenance orders",
        MAINTENANCE_ORDER_COMPLETE: "Complete maintenance orders (record actual cost)",
        MAINTENANCE_PLAN_READ: "Read maintenance plans",
        MAINTENANCE_PLAN_MANAGE: "Create, edit, activate and deactivate maintenance plans",
        MAINTENANCE_PLAN_RUN: "Run preventive maintenance generation",
    },
)

# --- Maintenance-order document type, numbering + docflow links (PLAN 9.2, D-051) ---------------
# A maintenance order IS a posted document in the D-012 sense (it registers in core_documents and
# claims a gapless number at creation — the production-order / inspection-lot precedent; unlike the
# equipment / plan masters, which carry only a user code). The prefix is "MNT-" (see module
# docstring): distinct from MO- (manufacturing) and every other module prefix.
MAINTENANCE_ORDER_DOC_TYPE = "maintenance.order"
MAINTENANCE_ORDER_SEQUENCE_NAME = "maintenance.order"
MAINTENANCE_ORDER_NUMBER_PREFIX = "MNT"
MAINTENANCE_ORDER_NUMBER_PADDING = 5

# Docflow edge (D-012/D-051): a preventive PLAN's document → 'generates' → the maintenance-order
# document the generation run creates. The plan is a master, so it ALSO registers a document (so it
# can be the predecessor of the orders it spawns — the only master in this module that does, because
# only the plan is a docflow predecessor). The order also carries ``maintenance_plan_id`` on its row
# (the durable column link), mirroring the planned-order ``converted_document_id`` pattern.
MAINTENANCE_PLAN_DOC_TYPE = "maintenance.plan"
PLAN_GENERATES_ORDER_LINK = "generates"
