"""Maintenance-order lifecycle (PLAN 9.2, D-051): create corrective, schedule / start / complete /
cancel + reads.

A CORRECTIVE order is created ad-hoc against ACTIVE equipment; a PREVENTIVE order is generated by a
plan's run (in plans.py, which calls ``create_generated_order`` here). Both register a document and
claim the gapless MNT- number at creation (the production-order precedent). COMPLETE records the
``actual_cost`` ON THE ORDER (record-only — no GL posting in v1, D-051: the parity scope is
"corrective/preventive orders", not full work-order costing; a GL posting through the cost centre is
a documented later).

``from __future__ import annotations`` keeps ``Page[MaintenanceOrder]`` a string at import.
"""

from __future__ import annotations

import uuid
from datetime import date

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core import docflow
from app.core.exceptions import ConflictError, NotFoundError, ValidationFailedError
from app.core.numbering import claim_number, ensure_sequence
from app.core.pagination import DEFAULT_LIMIT, OrderKey, SortDirection, filter_fingerprint, paginate
from app.core.schemas import Page
from app.modules.maintenance.constants import (
    MAINTENANCE_ORDER_DOC_TYPE,
    MAINTENANCE_ORDER_NUMBER_PADDING,
    MAINTENANCE_ORDER_NUMBER_PREFIX,
    MAINTENANCE_ORDER_SEQUENCE_NAME,
    EquipmentStatus,
    MaintenanceOrderStatus,
    MaintenanceOrderType,
)
from app.modules.maintenance.models import MaintenanceOrder
from app.modules.maintenance.schemas import (
    CompleteOrderRequest,
    MaintenanceOrderCreate,
    MaintenanceOrderUpdate,
)
from app.modules.maintenance.service.equipment import get_equipment

# Statuses an order can no longer be edited/scheduled/started/cancelled from (terminal).
_TERMINAL = (MaintenanceOrderStatus.COMPLETED, MaintenanceOrderStatus.CANCELLED)


async def get_maintenance_order(
    session: AsyncSession, tenant_id: uuid.UUID, order_id: uuid.UUID
) -> MaintenanceOrder:
    order = await session.get(MaintenanceOrder, order_id)
    if order is None or order.tenant_id != tenant_id:
        raise NotFoundError(
            message="Maintenance order not found",
            code="maintenance.order_not_found",
        )
    return order


async def _claim_order_number(
    session: AsyncSession, tenant_id: uuid.UUID, on_date: date
) -> str:
    """Ensure the MNT- sequence exists for the tenant and claim the next gapless number (D-012)."""
    await ensure_sequence(
        session,
        tenant_id,
        MAINTENANCE_ORDER_SEQUENCE_NAME,
        MAINTENANCE_ORDER_NUMBER_PREFIX,
        MAINTENANCE_ORDER_NUMBER_PADDING,
        year_reset=True,
    )
    return await claim_number(
        session, tenant_id, MAINTENANCE_ORDER_SEQUENCE_NAME, on_date=on_date
    )


async def _insert_order(
    session: AsyncSession,
    tenant_id: uuid.UUID,
    *,
    order_type: MaintenanceOrderType,
    status: MaintenanceOrderStatus,
    equipment_id: uuid.UUID,
    description: str,
    scheduled_date: date,
    maintenance_plan_id: uuid.UUID | None,
    estimated_cost,
    assigned_to: uuid.UUID | None,
    notes: str | None,
    on_date: date,
) -> MaintenanceOrder:
    """Register the order document, claim its gapless MNT- number, persist the order row (D-012).
    The shared insert behind both the corrective create and the plan-generated create."""
    order_id = uuid.uuid4()
    document = await docflow.register_document(
        session,
        tenant_id,
        MAINTENANCE_ORDER_DOC_TYPE,
        order_id,
        doc_number=None,
        status=status.value,
    )
    number = await _claim_order_number(session, tenant_id, on_date)
    order = MaintenanceOrder(
        id=order_id,
        tenant_id=tenant_id,
        document_id=document.id,
        order_number=number,
        order_type=order_type.value,
        status=status.value,
        equipment_id=equipment_id,
        maintenance_plan_id=maintenance_plan_id,
        description=description,
        scheduled_date=scheduled_date,
        estimated_cost=estimated_cost,
        assigned_to=assigned_to,
        notes=notes,
    )
    session.add(order)
    await session.flush()
    await docflow.set_document_status(
        session, tenant_id, document.id, doc_number=number, status=status.value
    )
    return order


async def create_corrective(
    session: AsyncSession, tenant_id: uuid.UUID, payload: MaintenanceOrderCreate
) -> MaintenanceOrder:
    """Create a CORRECTIVE maintenance order ad-hoc (D-051). The equipment must exist AND be ACTIVE
    (a maintenance order targets equipment in service — an INACTIVE/RETIRED unit is rejected 422).
    Born SCHEDULED when a ``scheduled_date`` is given, else DRAFT (it is scheduled later via the
    action). Registers the document + claims the MNT- number."""
    equipment = await get_equipment(session, tenant_id, payload.equipment_id)
    if EquipmentStatus(equipment.status) != EquipmentStatus.ACTIVE:
        raise ValidationFailedError(
            message="A maintenance order can only target ACTIVE equipment",
            code="maintenance.equipment_not_active",
            details={"equipment_id": str(payload.equipment_id), "status": equipment.status},
        )
    scheduled = payload.scheduled_date
    status = (
        MaintenanceOrderStatus.SCHEDULED
        if scheduled is not None
        else MaintenanceOrderStatus.DRAFT
    )
    return await _insert_order(
        session,
        tenant_id,
        order_type=MaintenanceOrderType.CORRECTIVE,
        status=status,
        equipment_id=payload.equipment_id,
        description=payload.description,
        # A DRAFT order still needs a scheduled_date column value (NOT NULL); default it to today
        # until the schedule action sets the real planned date.
        scheduled_date=scheduled if scheduled is not None else date.today(),
        maintenance_plan_id=None,
        estimated_cost=payload.estimated_cost,
        assigned_to=payload.assigned_to,
        notes=payload.notes,
        on_date=date.today(),
    )


async def create_generated_order(
    session: AsyncSession,
    tenant_id: uuid.UUID,
    *,
    equipment_id: uuid.UUID,
    maintenance_plan_id: uuid.UUID,
    description: str,
    scheduled_date: date,
    estimated_cost,
) -> MaintenanceOrder:
    """Create a PREVENTIVE order from a plan's run (D-051) — born SCHEDULED at the plan's due date,
    linked to the plan. Called by plans.run_preventive_maintenance; the plan→order docflow edge is
    written by the caller (it owns the plan document)."""
    return await _insert_order(
        session,
        tenant_id,
        order_type=MaintenanceOrderType.PREVENTIVE,
        status=MaintenanceOrderStatus.SCHEDULED,
        equipment_id=equipment_id,
        description=description,
        scheduled_date=scheduled_date,
        maintenance_plan_id=maintenance_plan_id,
        estimated_cost=estimated_cost,
        assigned_to=None,
        notes=None,
        on_date=scheduled_date,
    )


async def update_order(
    session: AsyncSession,
    tenant_id: uuid.UUID,
    order_id: uuid.UUID,
    payload: MaintenanceOrderUpdate,
) -> MaintenanceOrder:
    """Partial update of a non-terminal order's editable fields (D-010: mutate the loaded object).
    A COMPLETED/CANCELLED order is immutable (409)."""
    order = await get_maintenance_order(session, tenant_id, order_id)
    if MaintenanceOrderStatus(order.status) in _TERMINAL:
        raise ConflictError(
            message=f"A {order.status} maintenance order cannot be edited",
            code="maintenance.order_terminal",
            details={"order_id": str(order_id), "status": order.status},
        )
    for field, value in payload.model_dump(exclude_unset=True).items():
        setattr(order, field, value)
    await session.flush()
    return order


async def _transition(
    session: AsyncSession,
    order: MaintenanceOrder,
    tenant_id: uuid.UUID,
    new_status: MaintenanceOrderStatus,
) -> None:
    """Set the order + its registry document to ``new_status`` in the owning transaction."""
    order.status = new_status.value
    await session.flush()
    await docflow.set_document_status(
        session, tenant_id, order.document_id, status=new_status.value
    )


async def schedule_order(
    session: AsyncSession,
    tenant_id: uuid.UUID,
    order_id: uuid.UUID,
    scheduled_date: date,
) -> MaintenanceOrder:
    """Schedule a DRAFT order (D-051): DRAFT → SCHEDULED with the planned date. An already-SCHEDULED
    order may be re-scheduled (the date is updated, status unchanged). A started/terminal order
    cannot be scheduled (409)."""
    order = await get_maintenance_order(session, tenant_id, order_id)
    status = MaintenanceOrderStatus(order.status)
    if status not in (MaintenanceOrderStatus.DRAFT, MaintenanceOrderStatus.SCHEDULED):
        raise ConflictError(
            message=f"A {order.status} maintenance order cannot be scheduled",
            code="maintenance.order_not_schedulable",
            details={"order_id": str(order_id), "status": order.status},
        )
    order.scheduled_date = scheduled_date
    if status == MaintenanceOrderStatus.DRAFT:
        await _transition(session, order, tenant_id, MaintenanceOrderStatus.SCHEDULED)
    else:
        await session.flush()
    return order


async def start_order(
    session: AsyncSession, tenant_id: uuid.UUID, order_id: uuid.UUID
) -> MaintenanceOrder:
    """Start work on a SCHEDULED order (D-051): SCHEDULED → IN_PROGRESS. A DRAFT order must be
    scheduled first; a started/terminal order cannot be started again (409)."""
    order = await get_maintenance_order(session, tenant_id, order_id)
    if MaintenanceOrderStatus(order.status) != MaintenanceOrderStatus.SCHEDULED:
        raise ConflictError(
            message=f"A {order.status} maintenance order cannot be started",
            code="maintenance.order_not_startable",
            details={"order_id": str(order_id), "status": order.status},
        )
    await _transition(session, order, tenant_id, MaintenanceOrderStatus.IN_PROGRESS)
    return order


async def complete_order(
    session: AsyncSession,
    tenant_id: uuid.UUID,
    order_id: uuid.UUID,
    payload: CompleteOrderRequest,
) -> MaintenanceOrder:
    """Complete an order (D-051): SCHEDULED/IN_PROGRESS → COMPLETED, recording ``actual_cost`` and
    the completion date (record-only — no GL posting in v1; the cost lives on the order, D-051). A
    DRAFT/terminal order cannot be completed (409)."""
    order = await get_maintenance_order(session, tenant_id, order_id)
    status = MaintenanceOrderStatus(order.status)
    if status not in (
        MaintenanceOrderStatus.SCHEDULED,
        MaintenanceOrderStatus.IN_PROGRESS,
    ):
        raise ConflictError(
            message=f"A {order.status} maintenance order cannot be completed",
            code="maintenance.order_not_completable",
            details={"order_id": str(order_id), "status": order.status},
        )
    order.actual_cost = payload.actual_cost
    order.completed_date = payload.completed_date or date.today()
    await _transition(session, order, tenant_id, MaintenanceOrderStatus.COMPLETED)
    return order


async def cancel_order(
    session: AsyncSession, tenant_id: uuid.UUID, order_id: uuid.UUID
) -> MaintenanceOrder:
    """Cancel a non-terminal order (D-051): DRAFT/SCHEDULED/IN_PROGRESS → CANCELLED. A
    COMPLETED/CANCELLED order is terminal (409)."""
    order = await get_maintenance_order(session, tenant_id, order_id)
    if MaintenanceOrderStatus(order.status) in _TERMINAL:
        raise ConflictError(
            message=f"A {order.status} maintenance order cannot be cancelled",
            code="maintenance.order_not_cancellable",
            details={"order_id": str(order_id), "status": order.status},
        )
    await _transition(session, order, tenant_id, MaintenanceOrderStatus.CANCELLED)
    return order


async def list_maintenance_orders(
    session: AsyncSession,
    tenant_id: uuid.UUID,
    *,
    equipment_id: uuid.UUID | None = None,
    order_type: MaintenanceOrderType | None = None,
    status: MaintenanceOrderStatus | None = None,
    cursor: str | None = None,
    limit: int = DEFAULT_LIMIT,
) -> Page[MaintenanceOrder]:
    """Keyset-paginated maintenance orders ordered by order_number (D-014). The
    equipment/type/status filters narrow the set (index-served by (tenant, equipment, status) /
    (tenant, status, scheduled_date)) and fold into the cursor fingerprint."""
    stmt = select(MaintenanceOrder).where(MaintenanceOrder.tenant_id == tenant_id)
    if equipment_id is not None:
        stmt = stmt.where(MaintenanceOrder.equipment_id == equipment_id)
    if order_type is not None:
        stmt = stmt.where(MaintenanceOrder.order_type == order_type.value)
    if status is not None:
        stmt = stmt.where(MaintenanceOrder.status == status.value)
    fingerprint = filter_fingerprint(equipment_id, order_type, status)
    return await paginate(
        session,
        stmt,
        order_by=[OrderKey(MaintenanceOrder.order_number, SortDirection.ASC)],
        pk=MaintenanceOrder.id,
        cursor=cursor,
        limit=limit,
        filters=fingerprint,
    )
