"""The Alembic chain runs on a fresh SQLite file (D-022) and build_engine
connections enforce foreign keys via the PRAGMA listener (D-007)."""

import sqlite3
import uuid
from collections.abc import Callable
from contextlib import closing
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from sqlalchemy import text
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncEngine

from app.core.auth import API_KEY_PREFIX
from app.core.db import build_engine
from app.core.models import ApiKey
from app.modules.industry.schemas import OnboardTenantRequest


def test_alembic_upgrade_head_succeeds_on_fresh_sqlite(
    tmp_path: Path, make_alembic_config: Callable[[str], Config]
) -> None:
    db_path = tmp_path / "fresh.sqlite"
    config = make_alembic_config(f"sqlite+aiosqlite:///{db_path}")

    command.upgrade(config, "head")

    head = ScriptDirectory.from_config(config).get_current_head()
    with closing(sqlite3.connect(db_path)) as connection:
        rows = connection.execute("SELECT version_num FROM alembic_version").fetchall()
    assert rows == [(head,)]


def test_0002_creates_tenant_tables_and_downgrade_removes_them(
    tmp_path: Path, make_alembic_config: Callable[[str], Config]
) -> None:
    db_path = tmp_path / "tenants.sqlite"
    config = make_alembic_config(f"sqlite+aiosqlite:///{db_path}")

    def table_names() -> set[str]:
        with closing(sqlite3.connect(db_path)) as connection:
            rows = connection.execute("SELECT name FROM sqlite_master WHERE type='table'")
            return {row[0] for row in rows}

    command.upgrade(config, "head")
    assert {"adm_tenants", "adm_tenant_settings"} <= table_names()

    command.downgrade(config, "0001")
    assert not ({"adm_tenants", "adm_tenant_settings"} & table_names())


def test_0045_backfills_applied_periods_from_last_accrual_period(
    tmp_path: Path, make_alembic_config: Callable[[str], Config]
) -> None:
    """#160: 0045 promotes each pre-existing balance's single last_accrual_period into an
    hr_leave_accruals guard row, so a post-upgrade re-run of that period stays idempotent."""
    db_path = tmp_path / "backfill.sqlite"
    config = make_alembic_config(f"sqlite+aiosqlite:///{db_path}")
    command.upgrade(config, "0044")

    tenant_id = uuid.uuid4().hex
    stamped_id, unstamped_id = uuid.uuid4().hex, uuid.uuid4().hex
    with closing(sqlite3.connect(db_path)) as connection:
        # FK enforcement is off on this raw connection, so the minimal parent set suffices:
        # the migration connection enforces FKs and the backfill row references adm_tenants.
        connection.execute(
            "INSERT INTO adm_tenants (id, slug, name) VALUES (?, 'bf', 'Backfill')",
            (tenant_id,),
        )
        connection.execute(
            "INSERT INTO hr_leave_balances "
            "(id, tenant_id, employee_id, leave_type_id, last_accrual_period) "
            "VALUES (?, ?, ?, ?, ?)",
            (stamped_id, tenant_id, uuid.uuid4().hex, uuid.uuid4().hex, "2026-06"),
        )
        connection.execute(
            "INSERT INTO hr_leave_balances "
            "(id, tenant_id, employee_id, leave_type_id, last_accrual_period) "
            "VALUES (?, ?, ?, ?, NULL)",
            (unstamped_id, tenant_id, uuid.uuid4().hex, uuid.uuid4().hex),
        )
        connection.commit()

    command.upgrade(config, "head")

    with closing(sqlite3.connect(db_path)) as connection:
        rows = connection.execute(
            "SELECT tenant_id, balance_id, period FROM hr_leave_accruals"
        ).fetchall()
    # Exactly the stamped balance was backfilled; the never-accrued one produced no guard row.
    assert rows == [(tenant_id, stamped_id, "2026-06")]


def test_alembic_autogenerate_reports_no_drift_against_the_models(
    tmp_path: Path, make_alembic_config: Callable[[str], Config]
) -> None:
    """The chain and Base.metadata agree — `alembic check` finds nothing left to generate.
    Drift means the deployed schema is not the one the models describe, and it is invisible
    until some query fails in production; catching it costs one migrated SQLite file."""
    config = make_alembic_config(f"sqlite+aiosqlite:///{tmp_path / 'drift.sqlite'}")
    command.upgrade(config, "head")

    command.check(config)  # raises AutogenerateDiffsDetected if the models moved


def test_0046_round_trips_and_downgrade_drops_the_table_and_its_indexes(
    tmp_path: Path, make_alembic_config: Callable[[str], Config]
) -> None:
    """0046 (core_api_keys) is reversible: upgrade -> downgrade -> upgrade leaves the same
    schema, and the downgrade leaves no orphaned index behind. A migration that only ever
    runs forwards is a migration nobody can back out of a bad deploy."""
    db_path = tmp_path / "apikeys.sqlite"
    config = make_alembic_config(f"sqlite+aiosqlite:///{db_path}")

    def objects() -> set[tuple[str, str]]:
        with closing(sqlite3.connect(db_path)) as connection:
            rows = connection.execute(
                "SELECT type, name FROM sqlite_master WHERE tbl_name = 'core_api_keys'"
            )
            # sqlite_autoindex_* names are positional; the explicit ones are what we assert on.
            return {(row[0], row[1]) for row in rows if not row[1].startswith("sqlite_autoindex")}

    command.upgrade(config, "head")
    after_first = objects()
    assert after_first == {
        ("table", "core_api_keys"),
        ("index", "ix_core_api_keys_tenant_id"),
        ("index", "ix_core_api_keys_tenant_id_user_id"),
    }

    # Roll back a POPULATED table: that is what backing out a bad deploy actually looks like,
    # and on SQLite a DROP under `PRAGMA foreign_keys=ON` (which env.py turns on) behaves
    # differently from dropping an empty one.
    with closing(sqlite3.connect(db_path)) as connection:
        tenant_id, user_id = uuid.uuid4().hex, uuid.uuid4().hex
        connection.execute(
            "INSERT INTO adm_tenants (id, slug, name) VALUES (?, 'rt', 'Roundtrip')", (tenant_id,)
        )
        connection.execute(
            "INSERT INTO core_users (id, tenant_id, email, password_hash) "
            "VALUES (?, ?, 'rt@example.test', 'x')",
            (user_id, tenant_id),
        )
        connection.execute(
            "INSERT INTO core_api_keys (id, tenant_id, user_id, name, prefix, secret_sha256) "
            "VALUES (?, ?, ?, 'k', 'atk_rt', ?)",
            (uuid.uuid4().hex, tenant_id, user_id, "a" * 64),
        )
        connection.commit()

    command.downgrade(config, "0045")
    assert objects() == set()

    command.upgrade(config, "head")
    assert objects() == after_first


async def test_0046_composite_tenant_fk_rejects_a_user_from_another_tenant(
    db_engine: AsyncEngine,
) -> None:
    """D-007 item 4 at the DB level: (tenant_id, user_id) -> core_users(tenant_id, id) means
    a key row can never point at a user of another tenant, even if application code slips."""
    tenant_a, tenant_b, user_a = uuid.uuid4().hex, uuid.uuid4().hex, uuid.uuid4().hex
    async with db_engine.begin() as conn:
        for tenant_id, slug in ((tenant_a, "fk-a"), (tenant_b, "fk-b")):
            await conn.execute(
                text("INSERT INTO adm_tenants (id, slug, name) VALUES (:id, :slug, :slug)"),
                {"id": tenant_id, "slug": slug},
            )
        await conn.execute(
            text(
                "INSERT INTO core_users (id, tenant_id, email, password_hash) "
                "VALUES (:id, :tid, 'a@example.test', 'x')"
            ),
            {"id": user_a, "tid": tenant_a},
        )

    async def insert_key(tenant_id: str, user_id: str, digest: str) -> None:
        async with db_engine.begin() as conn:
            await conn.execute(
                text(
                    "INSERT INTO core_api_keys "
                    "(id, tenant_id, user_id, name, prefix, secret_sha256) "
                    "VALUES (:id, :tid, :uid, 'k', 'atk_x', :digest)"
                ),
                {"id": uuid.uuid4().hex, "tid": tenant_id, "uid": user_id, "digest": digest},
            )

    # Tenant B's key pointing at tenant A's user: rejected by the composite FK.
    with pytest.raises(IntegrityError):
        await insert_key(tenant_b, user_a, "d" * 64)
    # The same insert in the owning tenant is accepted, so the rejection is the FK and not
    # some unrelated NOT NULL.
    await insert_key(tenant_a, user_a, "d" * 64)


async def test_0046_secret_digest_is_unique_across_tenants(db_engine: AsyncEngine) -> None:
    """uq_core_api_keys_secret_sha256 is global, not per-tenant: the digest is what the auth
    lookup keys on, so a collision across tenants would authenticate the wrong tenant."""
    digest = "e" * 64
    tenant_a, tenant_b, user_a, user_b = (uuid.uuid4().hex for _ in range(4))
    async with db_engine.begin() as conn:
        for tenant_id, user_id, slug in ((tenant_a, user_a, "uq-a"), (tenant_b, user_b, "uq-b")):
            await conn.execute(
                text("INSERT INTO adm_tenants (id, slug, name) VALUES (:id, :slug, :slug)"),
                {"id": tenant_id, "slug": slug},
            )
            await conn.execute(
                text(
                    "INSERT INTO core_users (id, tenant_id, email, password_hash) "
                    "VALUES (:id, :tid, 'u@example.test', 'x')"
                ),
                {"id": user_id, "tid": tenant_id},
            )
        await conn.execute(
            text(
                "INSERT INTO core_api_keys (id, tenant_id, user_id, name, prefix, secret_sha256) "
                "VALUES (:id, :tid, :uid, 'k', 'atk_uq-a', :digest)"
            ),
            {"id": uuid.uuid4().hex, "tid": tenant_a, "uid": user_a, "digest": digest},
        )

    with pytest.raises(IntegrityError):
        async with db_engine.begin() as conn:
            await conn.execute(
                text(
                    "INSERT INTO core_api_keys "
                    "(id, tenant_id, user_id, name, prefix, secret_sha256) "
                    "VALUES (:id, :tid, :uid, 'k', 'atk_uq-b', :digest)"
                ),
                {"id": uuid.uuid4().hex, "tid": tenant_b, "uid": user_b, "digest": digest},
            )


def test_core_api_keys_prefix_column_fits_the_longest_mintable_prefix() -> None:
    """D-003 tripwire: admin/service.py stores ``atk_<tenant slug>`` in ``prefix``. Overflowing
    a VARCHAR is a silent truncation-free no-op on SQLite and a hard error on Postgres, so the
    column width must cover the widest slug onboarding can mint. Widen the column (a migration)
    if OnboardTenantRequest.slug's max_length ever grows."""
    slug_cap = OnboardTenantRequest.model_fields["slug"].metadata[0].max_length
    prefix_cap = ApiKey.__table__.c.prefix.type.length
    assert prefix_cap >= len(f"{API_KEY_PREFIX}_") + slug_cap


async def test_build_engine_connections_enforce_foreign_keys(tmp_path: Path) -> None:
    engine = build_engine(f"sqlite+aiosqlite:///{tmp_path / 'fk.sqlite'}")
    try:
        async with engine.connect() as connection:
            result = await connection.execute(text("PRAGMA foreign_keys"))
            assert result.scalar() == 1
    finally:
        await engine.dispose()
